sonar.projectKey=OTSkit_OTSkit-client
sonar.organization=otskit
sonar.sources=src
sonar.tests=tests,e2e
sonar.exclusions=examples/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
